name: patterns_ipr
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  go_router: ^12.1.3
  logger: ^2.0.2+1
  snowfall:
    git: https://github.com/nograve/snowfall.git

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
